# -*- coding: utf-8 -*-
"""
Created on Mon Nov 14 16:55:31 2016

@author: Jens

run from abaqus python
execfile('GenerateInput.py')

"""

# run from abaqus python
# execfile('GenerateInput.py')

from abapy.mesh import Mesh, Nodes
from abapy.materials import Elastic


template = '''**----------------------------------
**INPUT FILE GENERATED BY GenerateInput.py
**----------------------------------
*HEADING
{0}
*PREPRINT, ECHO=NO, MODEL=NO, HISTORY=NO, CONTACT=NO
**----------------------------------
** PART
**----------------------------------
*PART, NAME = PART-1
{1}
*SOLID SECTION, ELSET = ALL_ELEMENTS, MATERIAL = {3}
*END PART
**----------------------------------
** MATERIALS
**----------------------------------
{2}
**----------------------------------
** HISTORY DATA
**----------------------------------
*STEP, PERTURBATION
10kN central load
*STATIC
*BOUNDARY
101, ENCASTRE
103, 2
*CLOAD
102, 2, -10.E3
*NODE print
U,
RF,
*EL PRINT
S,
*END STEP
'''



# create nodes
nlabels = [101,102,103,104,105]

x = [0.,1.,2.,0.5,1.5]
y = [0.,0.,0.,0.866,0.866]
z = [0.,0.,0.,0.,0.]

sets = {'mynodes': [101,102,103,104,105]}

nodes = Nodes(labels = nlabels, x = x, y = y, z = z, sets = sets)

mesh = Mesh(nodes = nodes)


# create mesh
mesh.add_element(label=11, connectivity = (101,102), space =1, name = 'T2D2', toset='mySet' )
mesh.add_element(label=12, connectivity = (102,103), space =1, name = 'T2D2', toset='mySet' )
mesh.add_element(label=13, connectivity = (101,104), space =1, name = 'T2D2', toset='mySet' )
mesh.add_element(label=14, connectivity = (102,104), space =1, name = 'T2D2', toset='mySet' )
mesh.add_element(label=15, connectivity = (102,105), space =1, name = 'T2D2', toset='mySet' )
mesh.add_element(label=16, connectivity = (103,105), space =1, name = 'T2D2', toset='mySet' )
mesh.add_element(label=17, connectivity = (104,105), space =1, name = 'T2D2', toset='mySet' )


# define material
steel = Elastic(labels='STEEL',E=200000000000.0,nu=0.300000000000)

# generate inp from template
heading = "Sample Heading"
out = template.format(heading,mesh.dump2inp(), steel.dump2inp(),steel.labels[0])

# write to file
file = open("Generated_INP.inp", 'w')
file.truncate()
file.write(out)
file.close()
